### ISSUE TITLE
使用rocketmq-replicator运行到connect-runtime环境中调用api接口出现问题

### ISSUE THREAD

**Issue by bobosmile1170556238** [apache/rocketmq-connect#131]
restful接口调用：
http://127.0.0.1:8088/connectors/rocketmq-replicator-name01?config={
 "connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator",
 "source-rocketmq":"10.174.32.22:1074",
 "source-acl-enable":"true",
 "source-access-key":"rocketmq2",
 "source-secret-key":"12345678",
 "target-rocketmq":"10.174.32.42:1078",
 "target-acl-enable":"true",
 "target-access-key":"rocketmq2",
 "target-secret-key":"12345678",
 "replicator-store-topic":"replicatorTopic",
 "source-group":"TopicTest-group",
 "task-divide-strategy":"0",
 "white-list":"TopicTest,TopicTest2",
 "source-cluster":"rocketmq-connect-replicator01",
 "target-cluster":"rocketmq-connect-replicator02",
 "task-parallelism":"2",
 "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"
 }

报错信息：
2022-05-10 17:04:38 INFO qtp1839337592-110 - config: { "connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator", "source-rocketmq":"10.174.32.22:1074", "source-acl-enable": "true", "source-access-key": "rocketmq2", "source-secret-key": "12345678", "target-rocketmq":"10.174.32.42:1078", "target-acl-enable": "true", "target-access-key": "rocketmq2", "target-secret-key": "12345678", "replicator-store-topic":"replicatorTopic", "connect-topicname":"replicatorTopic", "source-group": "TopicTest-group", "task-divide-strategy":"0", "white-list":"TopicTest,TopicTest2", "source-cluster":"rocketmq-connect-replicator01", "target-cluster":"rocketmq-connect-replicator02", "task-parallelism":"2", "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter" }
2022-05-10 17:04:38 ERROR qtp1839337592-110 - Handle createConnector error .
java.lang.ClassNotFoundException: org.apache.rocketmq.replicator.RmqSourceReplicator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.rocketmq.connect.runtime.service.ConfigManagementServiceImpl.putConnectorConfig(ConfigManagementServiceImpl.java:184)
        at org.apache.rocketmq.connect.runtime.rest.RestHandler.handleCreateConnector(RestHandler.java:146)
        at io.javalin.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:22)
        at io.javalin.Javalin.lambda$addHandler$0(Javalin.java:606)
        at io.javalin.core.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:46)
        at io.javalin.core.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:17)
        at io.javalin.core.JavalinServlet$service$1.invoke(JavalinServlet.kt:143)
        at io.javalin.core.JavalinServlet$service$2.invoke(JavalinServlet.kt:41)
        at io.javalin.core.JavalinServlet.service(JavalinServlet.kt:107)
        at io.javalin.core.util.JettyServerUtil$initialize$httpHandler$1.doHandle(JettyServerUtil.kt:72)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:750)

**Comment by bobosmile1170556238** [comment]
file-source和sink测试是正常的，但是rocketmq-replicator是有问题的，打包一切正常的

**Comment by odbozhou** [comment]
replicator适配了新的connect api。即将merged。
如果有兴趣可以一起review这个replicator的pr
https://github.com/apache/rocketmq-connect/pull/117

**Comment by odbozhou** [comment]
最新的replicator代码已经合并了，可以更新代码再试试，有问题及时沟通

**Comment by zhangjidi2016** [comment]
使用了下适配了新的connect api的rocketmq-replicator, 发现了几个小问题，记录在 #132 中了，帮忙看下 @odbozhou

**Comment by bobosmile1170556238** [comment]
好像还没有完全适配上，报文返回Request config key: connect-topicname，看样子好像是connect里的中转topic被定义成必须值了？

**Comment by odbozhou** [comment]
> 好像还没有完全适配上，报文返回Request config key: connect-topicname，看样子好像是connect里的中转topic被定义成必须值了？



> 好像还没有完全适配上，报文返回Request config key: connect-topicname，看样子好像是connect里的中转topic被定义成必须值了？

如果觉得有什么不合适的或者需要优化的地方，可以提下issue和pr，欢迎贡献

**Comment by odbozhou** [comment]
> 好像还没有完全适配上，报文返回Request config key: connect-topicname，看样子好像是connect里的中转topic被定义成必须值了？



> 好像还没有完全适配上，报文返回Request config key: connect-topicname，看样子好像是connect里的中转topic被定义成必须值了？

如果觉得有什么不合适的或者需要优化的地方，可以提下issue和pr，欢迎贡献
