### ISSUE TITLE
java.lang.AbstractMethodError: io.openmessaging.connector.api.component.connector.Connector.start

### ISSUE THREAD

**Issue by JasonRoyGoGo** [apache/rocketmq-connect#189]
2022-07-12 10:38:58 ERROR qtp1848289347-34 - Exception occurred while servicing http-request
java.lang.AbstractMethodError: io.openmessaging.connector.api.component.connector.Connector.start(Lio/openmessaging/KeyValue;)V
	at org.apache.rocketmq.connect.runtime.service.memory.MemoryConfigManagementServiceImpl.putConnectorConfig(MemoryConfigManagementServiceImpl.java:158)
	at org.apache.rocketmq.connect.runtime.rest.RestHandler.handleCreateConnector(RestHandler.java:145)
	at io.javalin.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:22)
	at io.javalin.Javalin.lambda$addHandler$0(Javalin.java:606)
	at io.javalin.core.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:46)
	at io.javalin.core.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:17)
	at io.javalin.core.JavalinServlet$service$1.invoke(JavalinServlet.kt:143)
	at io.javalin.core.JavalinServlet$service$2.invoke(JavalinServlet.kt:41)
	at io.javalin.core.JavalinServlet.service(JavalinServlet.kt:107)
	at io.javalin.core.util.JettyServerUtil$initialize$httpHandler$1.doHandle(JettyServerUtil.kt:72)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JasonRoyGoGo** [comment]
> 

调用接口报的错 http://localhost:8082/connectors/replicator-test?config={
"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator",
"connect-topicname":"test-topic",
"source-rocketmq":"10.20.9.49:9876",
"target-rocketmq":"10.20.9.57:9876",
"replicator-store-topic":"test-topic",
"white-list":"fileTopic",
"target-cluster":"DefaultCluster",
"source-cluster":"DefaultCluster",
"source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter",
"topic.rename.format":"rename-${topic}"
}

**Comment by JasonRoyGoGo** [comment]
@odbozhou rocketmq-replicator启动之后，调用接口报的错 [http://localhost:8082/connectors/replicator-test?config={](http://localhost:8082/connectors/replicator-test?config=%7B)
"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator",
"connect-topicname":"test-topic",
"source-rocketmq":"10.20.9.49:9876",
"target-rocketmq":"10.20.9.57:9876",
"replicator-store-topic":"test-topic",
"white-list":"fileTopic",
"target-cluster":"DefaultCluster",
"source-cluster":"DefaultCluster",
"source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter",
"topic.rename.format":"rename-${topic}"
}

**Comment by sunxiaojian** [comment]
> @odbozhou rocketmq-replicator启动之后，调用接口报的错 [http://localhost:8082/connectors/replicator-test?config={](http://localhost:8082/connectors/replicator-test?config=%7B) "connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator", "connect-topicname":"test-topic", "source-rocketmq":"10.20.9.49:9876", "target-rocketmq":"10.20.9.57:9876", "replicator-store-topic":"test-topic", "white-list":"fileTopic", "target-cluster":"DefaultCluster", "source-cluster":"DefaultCluster", "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter", "topic.rename.format":"rename-${topic}" }

是不是升级过， 从1.2， 升级到1.3 的

**Comment by sunxiaojian** [comment]
> io.openmessaging.connector.api.component.connector

看一下 rocketmq-replicator 的  <openmessaging.connector.version> 是否和runtime的版本一致，如果不一致需要升级 replicator的版本为0.1.3

**Comment by JasonRoyGoGo** [comment]
> openmessaging.connector.version

只升级到0.1.3， rocketmq-replicator编译时会报错
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceReplicator.java:[101,21] 不兼容的类型: io.openmessaging.connector.api.component.connector.ConnectorContext无法转换为io.openmessagi
ng.KeyValue
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceReplicator.java:[156,5] 方法不会覆盖或实现超类型的方法
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceReplicator.java:[174,5] 方法不会覆盖或实现超类型的方法
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceReplicator.java:[179,5] 方法不会覆盖或实现超类型的方法
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceTask.java:[56,8] org.apache.rocketmq.replicator.RmqSourceTask不是抽象的, 并且未覆盖io.openmessaging.connector.api.component.Compon
ent中的抽象方法start(io.openmessaging.KeyValue)
[ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
licator/RmqSourceTask.java:[89,5] 方法不会覆盖或实现超类型的方法

**Comment by sunxiaojian** [comment]
> > openmessaging.connector.version
> > @sunxiaojian
> > 只升级到0.1.3， rocketmq-replicator编译时会报错
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceReplicator.java:[101,21] 不兼容的类型: io.openmessaging.connector.api.component.connector.ConnectorContext无法转换为io.openmessagi
> > ng.KeyValue
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceReplicator.java:[156,5] 方法不会覆盖或实现超类型的方法
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceReplicator.java:[174,5] 方法不会覆盖或实现超类型的方法
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceReplicator.java:[179,5] 方法不会覆盖或实现超类型的方法
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceTask.java:[56,8] org.apache.rocketmq.replicator.RmqSourceTask不是抽象的, 并且未覆盖io.openmessaging.connector.api.component.Compon
> > ent中的抽象方法start(io.openmessaging.KeyValue)
> > [ERROR] /C:/Users/HP/Downloads/rocketmq-connect-master/rocketmq-connect-master/connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/rep
> > licator/RmqSourceTask.java:[89,5] 方法不会覆盖或实现超类型的方法

嗯，不能只升级版本，因为0.1.3的api 和 0.1.2的做了优化，我来升级一下

**Comment by sunxiaojian** [comment]
> [http://xxxxx:32715/connectors/replicator-test-2?config={"connector-class":"org.apache.rockentmq.replicator.RmqSourceReplicator","source-rocketmq":"10.10.35.151:31088","target-rocketmq":"10.10.35.151:32240","replicator-store-topic":"replicator-store-topic","task-divide-strategy":"0","white-list":"","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"rocketmq2","source-cluster":"rocketmq1","connect-topicname":""}](http://xxxxx:32715/connectors/replicator-test-2?config=%7B%22connector-class%22:%22org.apache.rockentmq.replicator.RmqSourceReplicator%22,%22source-rocketmq%22:%2210.10.35.151:31088%22,%22target-rocketmq%22:%2210.10.35.151:32240%22,%22replicator-store-topic%22:%22replicator-store-topic%22,%22task-divide-strategy%22:%220%22,%22white-list%22:%22%22,%22task-parallelism%22:%222%22,%22source-record-converter%22:%22org.apache.rocketmq.connect.runtime.converter.JsonConverter%22,%22target-cluster%22:%22rocketmq2%22,%22source-cluster%22:%22rocketmq1%22,%22connect-topicname%22:%22%22%7D)
> 
> 这些参数有什么具体要求吗？源集群中又有topic,并且topic中有消息，无法进行同步。没有task

文档中心有快速入门，可以按照demo跑一下试试 ？

**Comment by wongearl** [comment]
![9eda860ffc8f975d7e56afa219744af](https://user-images.githubusercontent.com/36498442/179431837-d207dca0-6a09-47e4-9746-04c125903145.png)
@sunxiaojian [sunxiaojian](https://github.com/sunxiaojian)你好，就是按照demo和文档指导就行操作，看日志已经连接到broker，但是就是数据没有同步过去。

**Comment by sunxiaojian** [comment]
> ![9eda860ffc8f975d7e56afa219744af](https://user-images.githubusercontent.com/36498442/179431837-d207dca0-6a09-47e4-9746-04c125903145.png) @sunxiaojian [sunxiaojian](https://github.com/sunxiaojian)你好，就是按照demo和文档指导就行操作，看日志已经连接到broker，但是就是数据没有同步过去。

OK，应该是配置有问题，我去看一下

**Comment by wongearl** [comment]
你好大神，@sunxiaojian 觉得问题是出在哪？启动配置的话，就是配置了一个单独的rocketmq给runtime用。

**Comment by sunxiaojian** [comment]
> 你好大神，@sunxiaojian 觉得问题是出在哪？启动配置的话，就是配置了一个单独的rocketmq给runtime用。

已跑通，我先修复个问题，你再试一下，下面是我的配置
{
    "connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator",
    "source-rocketmq":"localhost:9876",
    "target-rocketmq":"localhost:9876",
    "connect-topicname":"test-topic",
    "replicator-store-topic":"replicatorTopic",
    "taskDivideStrategy":"0",
    "white-list":"connect-topicname-jdbc-02",
    "target-cluster":"DefaultCluster",
    "source-cluster":"DefaultCluster",
    "topic.rename.format": "rename-${topic}",
    "task-parallelism":"2",
    "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter"
}

**Comment by sunxiaojian** [comment]
> 你好大神，@sunxiaojian 觉得问题是出在哪？启动配置的话，就是配置了一个单独的rocketmq给runtime用。

你的配置贴一下

**Comment by wongearl** [comment]
> > 你好大神，@sunxiaojian 觉得问题是出在哪？启动配置的话，就是配置了一个单独的rocketmq给runtime用。
> 
> 你的配置贴一下
runtime配置文件如下：

workerId=standalone-worker
storePathRootDir=/rocketmq-connect/storeRoot

## Http port for user to access REST API
httpPort=8082

# Rocketmq namesrvAddr
namesrvAddr=localhost:9876

# RocketMQ acl
#aclEnable=false
#accessKey=rocketmq
#secretKey=12345678

#autoCreateGroupEnable=false
clusterName="DefaultCluster"

# Source or sink connector jar file dir,The default value is rocketmq-connect-sample
pluginPaths=/rocketmq-connect/connectors/rocketmq-replicator/target/rocketmq-replicator-0.1.0-SNAPSHOT-jar-with-dependencies.jar


发起同步的请求是这样的：
[http://xxxxx:32715/connectors/replicator-test-2?config={"connector-class":"org.apache.rockentmq.replicator.RmqSourceReplicator","source-rocketmq":"10.10.35.151:31088","target-rocketmq":"10.10.35.151:32240","replicator-store-topic":"replicator-store-topic","task-divide-strategy":"0","white-list":"","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"rocketmq2","source-cluster":"rocketmq1","connect-topicname":""}](http://xxxxx:32715/connectors/replicator-test-2?config=%7B%22connector-class%22:%22org.apache.rockentmq.replicator.RmqSourceReplicator%22,%22source-rocketmq%22:%2210.10.35.151:31088%22,%22target-rocketmq%22:%2210.10.35.151:32240%22,%22replicator-store-topic%22:%22replicator-store-topic%22,%22task-divide-strategy%22:%220%22,%22white-list%22:%22%22,%22task-parallelism%22:%222%22,%22source-record-converter%22:%22org.apache.rocketmq.connect.runtime.converter.JsonConverter%22,%22target-cluster%22:%22rocketmq2%22,%22source-cluster%22:%22rocketmq1%22,%22connect-topicname%22:%22%22%7D)


white-list参数不填，意思是同步所有topic吗？

**Comment by wongearl** [comment]
> @wongearl recently @sunxiaojian is refactoring rocketmq connect architecture, some connectors also needs to upgrade to adapt the new connect architecture, such as hudi connector, replicator connector, are you interested in participating together?

Thank you very much, but I'm not familiar with Java.

**Comment by wongearl** [comment]
@sunxiaojian， 非常感谢您的回答，还有问题需要请教一下：
1. connect-standalone.conf 文件里面配置rcoketMq是单独rocketmq集群给runtime用的吗我之前是这样理解的，看上面的回答，像是在这里配置的target-cluster rocketmq.
2. 我想同步的是两个rocketmq集群间的同步，即将源rocketmq的数据同步到target rocketmq, white-list不写的情况，我的预期是会将源rocketmq集群的topic在目标rocketmq集群创建，并且将消息同步过去，是这样的吗？
3. replicator-store-topic参数我看文档说是在runtime配置rocketmq集群创建，又说在源rocketmq集群创建，这个应该在哪创建？
4. 这个文档https://rocketmq-1.gitbook.io/rocketmq-connector/quick-start/runtime-qs说的topic我都已经在runtime配置里的rockertmq集群创建，这个没问题吧？
