### ISSUE TITLE
The rocketmq connect HTTP package cannot be loaded when starting through the rocketmq connect runtime.

### ISSUE THREAD

**Issue by zhaohai1299002788** [apache/rocketmq-connect#20]
报错信息如下 ：
Connected to the target VM, address: '127.0.0.1:57904', transport: 'socket'
10:02:05.114 [main] INFO  o.a.r.connect.runtime.utils.Plugin - Loading plugin from: D:\connector-plugins\rocketmq-connect-http-0.0.1-SNAPSHOT-jar-with-dependencies.jar
10:02:05.121 [main] DEBUG o.a.r.connect.runtime.utils.Plugin - Loading plugin urls: [file:/D:/connector-plugins/rocketmq-connect-http-0.0.1-SNAPSHOT-jar-with-dependencies.jar]
10:02:05.211 [main] DEBUG org.reflections.Reflections - going to scan these urls: [file:/D:/connector-plugins/rocketmq-connect-http-0.0.1-SNAPSHOT-jar-with-dependencies.jar]
10:02:05.223 [org.reflections-scanner-1] DEBUG org.reflections.Reflections - [Thread[org.reflections-scanner-1,5,main]] scanning file:/D:/connector-plugins/rocketmq-connect-http-0.0.1-SNAPSHOT-jar-with-dependencies.jar
10:02:05.682 [main] INFO  org.reflections.Reflections - Reflections took 451 ms to scan 1 urls, producing 341 keys and 928 values [using 8 cores]
10:02:05.689 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.text.Format
10:02:05.689 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Cloneable -> java.text.Format
10:02:05.692 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Runnable -> java.lang.Thread
10:02:05.695 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.ThreadLocal -> java.lang.InheritableThreadLocal
10:02:05.695 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Calendar -> java.util.GregorianCalendar
10:02:05.695 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.util.Calendar
10:02:05.695 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Cloneable -> java.util.Calendar
10:02:05.695 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Comparable -> java.util.Calendar
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.List -> java.util.concurrent.CopyOnWriteArrayList
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Collection -> java.util.List
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Iterable -> java.util.Collection
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.RandomAccess -> java.util.concurrent.CopyOnWriteArrayList
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Cloneable -> java.util.concurrent.CopyOnWriteArrayList
10:02:05.697 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.util.concurrent.CopyOnWriteArrayList
10:02:05.698 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.HashMap -> java.util.LinkedHashMap
10:02:05.698 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.AbstractMap -> java.util.HashMap
10:02:05.698 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Map -> java.util.AbstractMap
10:02:05.699 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Map -> java.util.HashMap
10:02:05.699 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Cloneable -> java.util.HashMap
10:02:05.699 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.util.HashMap
10:02:05.699 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Map -> java.util.LinkedHashMap
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Exception -> java.io.IOException
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Throwable -> java.lang.Exception
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.lang.Throwable
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype org.xml.sax.EntityResolver -> org.xml.sax.helpers.DefaultHandler
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype org.xml.sax.DTDHandler -> org.xml.sax.helpers.DefaultHandler
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype org.xml.sax.ContentHandler -> org.xml.sax.helpers.DefaultHandler
10:02:05.701 [main] DEBUG org.reflections.Reflections - expanded subtype org.xml.sax.ErrorHandler -> org.xml.sax.helpers.DefaultHandler
10:02:05.702 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.reflect.Type -> java.lang.reflect.ParameterizedType
10:02:05.717 [main] WARN  org.reflections.Reflections - could not get type for name javax.ws.rs.ext.MessageBodyReader from any class loader
org.reflections.ReflectionsException: could not get type for name javax.ws.rs.ext.MessageBodyReader
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.718 [main] WARN  org.reflections.Reflections - could not get type for name org.springframework.http.converter.GenericHttpMessageConverter from any class loader
org.reflections.ReflectionsException: could not get type for name org.springframework.http.converter.GenericHttpMessageConverter
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.http.converter.GenericHttpMessageConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.720 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Iterator -> java.util.ListIterator
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.InputStream -> java.io.ObjectInputStream
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Closeable -> java.io.InputStream
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.AutoCloseable -> java.io.Closeable
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.ObjectInput -> java.io.ObjectInputStream
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.DataInput -> java.io.ObjectInput
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.AutoCloseable -> java.io.ObjectInput
10:02:05.721 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.ObjectStreamConstants -> java.io.ObjectInputStream
10:02:05.723 [main] WARN  org.reflections.Reflections - could not get type for name javax.ws.rs.ext.MessageBodyWriter from any class loader
org.reflections.ReflectionsException: could not get type for name javax.ws.rs.ext.MessageBodyWriter
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.724 [main] WARN  org.reflections.Reflections - could not get type for name javax.jms.MessageListener from any class loader
org.reflections.ReflectionsException: could not get type for name javax.jms.MessageListener
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.jms.MessageListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.726 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.Collection -> java.util.AbstractCollection
10:02:05.726 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Iterable -> java.util.Collection
10:02:05.727 [main] DEBUG org.reflections.Reflections - expanded subtype java.util.EventListener -> javax.servlet.ServletContextListener
10:02:05.729 [main] WARN  org.reflections.Reflections - could not get type for name org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice from any class loader
org.reflections.ReflectionsException: could not get type for name org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.731 [main] WARN  org.reflections.Reflections - could not get type for name retrofit2.Converter from any class loader
org.reflections.ReflectionsException: could not get type for name retrofit2.Converter
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: retrofit2.Converter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.731 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.util.TimeZone
10:02:05.731 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Cloneable -> java.util.TimeZone
10:02:05.735 [main] WARN  org.reflections.Reflections - could not get type for name org.springframework.messaging.converter.AbstractMessageConverter from any class loader
org.reflections.ReflectionsException: could not get type for name org.springframework.messaging.converter.AbstractMessageConverter
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.messaging.converter.AbstractMessageConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.740 [main] WARN  org.reflections.Reflections - could not get type for name javax.mail.Authenticator from any class loader
org.reflections.ReflectionsException: could not get type for name javax.mail.Authenticator
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.741 [main] WARN  org.reflections.Reflections - could not get type for name javax.ws.rs.core.Feature from any class loader
org.reflections.ReflectionsException: could not get type for name javax.ws.rs.core.Feature
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Feature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted
10:02:05.743 [main] WARN  org.reflections.Reflections - could not get type for name org.springframework.web.socket.sockjs.frame.AbstractSockJsMessageCodec from any class loader
org.reflections.ReflectionsException: could not get type for name org.springframework.web.socket.sockjs.frame.AbstractSockJsMessageCodec
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382) [reflections-0.9.12.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:140) [reflections-0.9.12.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin$PluginReflections.<init>(Plugin.java:116) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.doLoad(Plugin.java:92) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.registerPlugin(Plugin.java:158) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.loadPlugin(Plugin.java:73) [classes/:na]
	at org.apache.rocketmq.connect.runtime.utils.Plugin.initPlugin(Plugin.java:63) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectController.<init>(ConnectController.java:117) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.createConnectController(ConnectStartup.java:101) [classes/:na]
	at org.apache.rocketmq.connect.runtime.ConnectStartup.main(ConnectStartup.java:50) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.web.socket.sockjs.frame.AbstractSockJsMessageCodec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at org.apache.rocketmq.connect.runtime.utils.PluginClassLoader.loadClass(PluginClassLoader.java:66) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 10 common frames omitted

以下是配置信息 ：
![image](https://user-images.githubusercontent.com/33314633/158092331-38fa091b-a324-4b08-826e-0b803b6326f6.png)

![image](https://user-images.githubusercontent.com/33314633/158092653-08509560-49b6-4c47-bf8a-a1a39dd3e3f9.png)

**Comment by odbozhou** [comment]
Caused by: java.lang.ClassNotFoundException. Confirm that ClassNotFoundException classes are in the connector jar package

**Comment by zhaohai1299002788** [comment]
These missing classes are not used in the code. I don't know why these classes are loaded.By parsing the jar, you can see that the classes to be loaded exist in the jar.
![image](https://user-images.githubusercontent.com/33314633/158344152-cda583eb-88cd-43c5-bb77-089fc6a6e786.png)

**Comment by zhaohai1299002788** [comment]
The above log is just a startup exception and does not affect the start of connectors.
