### ISSUE TITLE
Potential NPE

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq-connect#234]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

when I exec `org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectController#start`

then cause NPE

> 
                java.lang.NullPointerException
	            at org.apache.rocketmq.connect.runtime.service.ClusterManagementServiceImpl.start(ClusterManagementServiceImpl.java:90)
	            at org.apache.rocketmq.connect.runtime.controller.AbstractConnectController.start(AbstractConnectController.java:108)
	            at org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectController.start(StandaloneConnectController.java:53)
	            at org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectControllerTest.startTest(StandaloneConnectControllerTest.java:63)
	            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	            at java.lang.reflect.Method.invoke(Method.java:498)
	            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	            at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	            at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	            at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	            at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	            at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:46)
	            at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	            at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	            at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	            at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	            at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	            at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	            at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	            at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	            at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:77)
	            at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:83)
	            at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	            at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)

The reason is that defaultMQPullConsumer is not initialized

- What is expected to see?

It do not occur NPE

- What did you see instead?

occur NPE

2. Please tell us about your environment:

master

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

we can initialize before start

In `org.apache.rocketmq.connect.runtime.controller.AbstractConnectController#start`

> 
         @Override
        public void start() {
            clusterManagementService.initialize(connectConfig);
            clusterManagementService.start();
            configManagementService.start();
            positionManagementService.start();
            worker.start();
            connectStatsService.start();
        }

**Comment by sunxiaojian** [comment]
Standalone does not need to initialize defaultMQPullConsumer

**Comment by sunxiaojian** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
> 
> * What did you do (The steps to reproduce)?
> 
> when I exec `org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectController#start`
> 
> then cause NPE
> 
> > 
> 
> ```
>             java.lang.NullPointerException
>             at org.apache.rocketmq.connect.runtime.service.ClusterManagementServiceImpl.start(ClusterManagementServiceImpl.java:90)
>             at org.apache.rocketmq.connect.runtime.controller.AbstractConnectController.start(AbstractConnectController.java:108)
>             at org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectController.start(StandaloneConnectController.java:53)
>             at org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectControllerTest.startTest(StandaloneConnectControllerTest.java:63)
>             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>             at java.lang.reflect.Method.invoke(Method.java:498)
>             at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
>             at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>             at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
>             at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>             at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
>             at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:46)
>             at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
>             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
>             at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
>             at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
>             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
>             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
>             at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
>             at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
>             at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
>             at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
>             at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
>             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
>             at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
>             at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:77)
>             at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:83)
>             at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
>             at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
> ```
> 
> The reason is that defaultMQPullConsumer is not initialized
> 
> * What is expected to see?
> 
> It do not occur NPE
> 
> * What did you see instead?
> 
> occur NPE
> 
> 2. Please tell us about your environment:
> 
> master
> 
> 4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
> 
> we can initialize before start
> 
> In `org.apache.rocketmq.connect.runtime.controller.AbstractConnectController#start`
> 
> > 
> 
> ```
>      @Override
>     public void start() {
>         clusterManagementService.initialize(connectConfig);
>         clusterManagementService.start();
>         configManagementService.start();
>         positionManagementService.start();
>         worker.start();
>         connectStatsService.start();
>     }
> ```

defaultMQPullConsumer

**Comment by sunxiaojian** [comment]
![image](https://user-images.githubusercontent.com/6446530/182782268-bede8329-6ffb-40d9-8e36-c972941ad05e.png)
It should have been initialized

**Comment by Oliverwqcwrw** [comment]
`org.apache.rocketmq.connect.runtime.controller.standalone.StandaloneConnectController#start`

> 
     public void start() {
        super.start();
        rebalanceService.start();
    }

It's called start, it's not initialized

**Comment by Oliverwqcwrw** [comment]
> ![image](https://user-images.githubusercontent.com/6446530/182782268-bede8329-6ffb-40d9-8e36-c972941ad05e.png) It should have been initialized

I understand your meaning
