### ISSUE TITLE
connect-runtime throw java.lang.StackOverflowError.

### ISSUE THREAD

**Issue by fireroundgithub** [apache/rocketmq-connect#376]
Please describe the issue you observed:
connect-runtime throw java.lang.StackOverflowError.

What did you do (The steps to reproduce)?
Modify the standalone configuration file, add plugin such as "connectors/rocketmq-connect-jdbc/target" to "pluginPaths". Then start StandaloneConnectStartup. Then try to start source connector:
  ```
POST /connectors/rocketmq-connect-jdbc HTTP/1.1
  Host: localhost:8082
  Content-Type: application/json
  
  {
    "connector.class":"org.apache.rocketmq.connect.jdbc.connector.JdbcSourceTask",
    "max.tasks":"2",
    "connection.url":"jdbc:mysql://localhost:3306",
    "connection.user":"wencheng",
    "connection.password":"1617",
    "table.whitelist":"db.table",
    "mode": "incrementing",
    "incrementing.column.name":"id",
    "timestamp.initial": -1,
    "key.converter":"org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter",
    "value.converter":"org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter"
  }
```

What is expected to see?
SourceConnector started as normal.

What did you see instead?
connect-runtime throw java.lang.StackOverflowError.

Please tell us about your environment:
OSX、JDK8.0

Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
```
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1005)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StackOverflowError: null
	at java.util.regex.Pattern$Slice.match(Pattern.java:3986)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
	at java.util.regex.Pattern$Begin.match(Pattern.java:3539)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
	at java.util.regex.Matcher.match(Matcher.java:1270)
	at java.util.regex.Matcher.matches(Matcher.java:604)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginUtils.shouldNotLoadInIsolation(PluginUtils.java:326)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:71)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:71)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:71)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:71)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at org.apache.rocketmq.connect.runtime.controller.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:71)
	at org.apache.rocketmq.connect.runtime.controller.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:375)
```

**Comment by fireroundgithub** [comment]
@odbozhou Hi, is there any way to avoid this problem temporarily?

**Comment by fireroundgithub** [comment]
Good! it works.
