### ISSUE TITLE
DistributedConnectControllerTest #startTest The port is still occupied after the method is executed

### ISSUE THREAD

**Issue by shy-share** [apache/rocketmq-connect#387]
After executing this method, it cannot be executed again and the error is reported because the port is already occupied.I want to fix him but I don't know where to start.Please provide some advice Thanks

java.net.BindException: Address already in use: bind

	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:127)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:501)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1218)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:965)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:210)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/50973219/205818443-ac9a036e-9051-4ed7-86f5-7d99e2390468.png)

**Comment by Oliverwqcwrw** [comment]
Hello @shy-share ,
There is a mockNameServer and mockBroker started before startTest starts, and maybe port 9876 or 10911 is occupied
You can stop ports 9876 and 10911 and try again

**Comment by shy-share** [comment]
> Hello @shy-share , There is a mockNameServer and mockBroker started before startTest starts, and maybe port 9876 or 10911 is occupied You can stop ports 9876 and 10911 and try again

I know, but the code is shutdown, but now the port is still occupied, so it should not be as expected, right?

**Comment by Oliverwqcwrw** [comment]
I tried running the UT, and the port closed after the method was executed

Hi @shy-share , How do  I reproduce this scene?

**Comment by shy-share** [comment]
> I tried running the UT, and the port closed after the method was executed
> 
> Hi @shy-share , How do I reproduce this scene?

@Oliverwqcwrw  Oh, i found the problem, it's because I started a docker desttop locally that caused the port conflict, I thought it was the error caused by executing the test method twice
