### ISSUE TITLE
debezium-mysql connector无法连接nameserver

### ISSUE THREAD

**Issue by shusley244** [apache/rocketmq-connect#545]
1. 使用demo中的文件同步，能连上nameserver，日志如下：
```
2024-12-09 17:22:59,469 INFO RocketmqClient - [persistAll] Group: connect-fileSinkConnector ClientId: 10.233.66.215@StateMachineService-414@StateMachineService-414@STREAM updateConsumeOffsetToBroker MessageQueue [topic=fileTopic, brokerName=broker-g0, queueId=15] 
```

文件同步实际演示效果符合预期。

2. 使用demo中的debezium-mysql connector时，日志报错却提示nameserver无法连接：

```
2024-12-09 17:22:54,707 INFO RocketmqClient - Created new MQClientInstance for clientId:[10.233.66.215@10.233.66.253:9876-a5b6bdca-089e-4303-a6ec-413f1258644d]
2024-12-09 17:22:54,707 INFO RocketmqClient - PullMessageService service started
2024-12-09 17:22:54,707 INFO RocketmqClient - the producer [CLIENT_INNER_PRODUCER] start OK. sendMessageWithVIPChannel=false
2024-12-09 17:22:54,707 INFO RocketmqClient - the client factory [10.233.66.215@10.233.66.253:9876-a5b6bdca-089e-4303-a6ec-413f1258644d] start OK
2024-12-09 17:22:54,707 INFO RocketmqClient - the producer [connector-producer-group] start OK. sendMessageWithVIPChannel=false
2024-12-09 17:22:54,707 INFO RocketmqClient - RebalanceService service started
2024-12-09 17:22:54,717 INFO RocketmqClient - the producer [CLIENT_INNER_PRODUCER] shutdown OK
2024-12-09 17:22:54,717 INFO RocketmqRemoting - new name server is chosen. OLD: null , NEW: 10.233.66.253:9876. namesrvIndex = 377
2024-12-09 17:22:54,717 INFO RocketmqClient - PullMessageService service end
2024-12-09 17:22:54,718 INFO RocketmqRemoting - createChannel: begin to connect remote host[10.233.66.253:9876] asynchronously
2024-12-09 17:22:54,718 INFO RocketmqRemoting - shutdown thread NettyEventExecutor interrupt false
2024-12-09 17:22:54,718 INFO RocketmqRemoting - join thread NettyEventExecutor elapsed time(ms) 0 90000
2024-12-09 17:22:54,719 INFO RocketmqClient - RebalanceService service end
2024-12-09 17:22:54,719 INFO RocketmqClient - the client factory [10.233.66.215@10.233.66.253:9876-a5b6bdca-089e-4303-a6ec-413f1258644d] shutdown OK
2024-12-09 17:22:54,719 WARN RocketmqRemoting - createChannel: connect remote host[10.233.66.253:9876] failed, AbstractBootstrap$PendingRegistrationPromise@36eb0d6a(failure: java.lang.IllegalStateException: executor not accepting a task)
java.lang.IllegalStateException: executor not accepting a task
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1012)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-12-09 17:22:54,719 INFO RocketmqClient - the producer [connector-producer-group] shutdown OK
2024-12-09 17:22:54,719 ERROR RocketmqClient - updateTopicRouteInfoFromNameServer Exception
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to [10.233.66.253:9876] failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateNameserverChannel(NettyRemotingClient.java:458)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateChannel(NettyRemotingClient.java:413)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:382)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1399)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1389)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:623)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:510)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:359)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:276)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-12-09 17:22:54,719 ERROR RocketmqClient - ScheduledTask updateTopicRouteInfoFromNameServer exception
java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to [10.233.66.253:9876] failed
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:680)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:510)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:359)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:276)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to [10.233.66.253:9876] failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateNameserverChannel(NettyRemotingClient.java:458)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateChannel(NettyRemotingClient.java:413)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:382)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1399)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1389)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:623)
        ... 9 more

2024-12-09 17:22:54,818 INFO RocketmqRemoting - NETTY CLIENT PIPELINE: CLOSE
2024-12-09 17:22:54,819 INFO RocketmqRemoting - closeChannel: the channel[10.233.66.253:9876] was removed from channel table
2024-12-09 17:22:54,819 INFO RocketmqRemoting - NETTY CLIENT PIPELINE: CLOSE
```

**Comment by shusley244** [comment]
debezium-mysql connector创建命令是：
```
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8082/connectors/mysql-test -d '{
"connector.class": "org.apache.rocketmq.connect.debezium.mysql.DebeziumMysqlConnector",
"max.task": "1",
"connect.topicname": "topic-cdc-dev-environment",
"kafka.transforms": "Unwrap",
"kafka.transforms.Unwrap.delete.handling.mode": "none",
"kafka.transforms.Unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
"kafka.transforms.Unwrap.add.headers": "op,source.db,source.table",
"database.history.skip.unparseable.ddl": true,
"database.history.name.srv.addr": "10.233.66.253:9876",
"database.history.rocketmq.topic": "db-history-debezium-topic",
"database.history.store.only.monitored.tables.ddl": true,
"include.schema.changes": false,
"database.server.name": "dbserver1",
"database.port": 3306,
"database.hostname": "10.233.59.60",
"database.connectionTimeZone": "UTC",
"database.user": "root",
"database.password": "******",
"table.include.list": "cloud.platform_dev_environment",
"max.batch.size": 50,
"database.include.list": "cloud",
"snapshot.mode": "when_needed",
"key.converter": "org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter",
"value.converter": "org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter"
}'
```
